name = "The Real New World"
author = "Singlain"
version = "1.5.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7692f2ddf6dfa72599d65a606f2d092203e15a3d6dcc57949ff87ea7078f641"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
