#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Mar 09 01:28:23 CET 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=6
shaderPack=TAA 3.1.zip